# --------------------------------
# Playbook: Configure dependencies for host system
# running python3 borgbackup instance
# Target: Ubuntu/Debian, apt package manager
# Docs: https://github.com/borgbackup/borg/blob/master/docs/installation.rst
# --------------------------------

- hosts: all
  remote_user: user
  become: yes

  tasks:
    - name: Python3 dependencies required by borgbackup
      block:
        - name: Configure packages on host
          apt:
            state: present
            name:
              - python3
              - python3-pip
              - python3-dev
              - python3-virtualenv
              - libacl1-dev
              - libacl1
              - libssl-dev
              - liblz4-dev
              - libzstd-dev
              - build-essential
              - pkg-config
              - python3-pkgconfig
              - libfuse-dev
              - fuse
              - libfuse3-dev
              - fuse3

# ----------------------------------
